[build]
publish = "/"  
command = "echo 'Building site...'" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
for = "/*"
[headers.values]
  Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
  Pragma = "no-cache"
  Expires = "0"
  Content-Encoding = "gzip"


[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true


